# Generated by Django 5.0.3 on 2024-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_post_images_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
